import { ArtDirectionPacketSchema, type ArtDirectionPacket } from './art-direction-schemas.ts';
import type { StoryContent, StoryMeta } from './fulfillment-types.ts';
import type { OrderRecord } from './orders.ts';
import { validateStoryboardCompleteness, type StoryboardValidation } from './storyboard-validator.ts';

export interface ArtDirectionPacketBuildInput {
  order: OrderRecord;
  story: StoryContent;
  storyMeta: StoryMeta;
}

export interface ArtDirectionPacketBuildResult {
  packet: ArtDirectionPacket;
  validation: StoryboardValidation;
  generatedAt: string;
  humanReviewStatus: NonNullable<OrderRecord['artDirectionHumanReviewStatus']>;
  humanReviewNotes: string | null;
}

export interface ArtDirectionPacketBuilderDeps {
  provider?: (input: ArtDirectionPacketBuildInput) => Promise<unknown>;
  now?: () => Date;
}

/**
 * Local/provider-injected packet builder.
 *
 * The default has no provider and returns null, so production behavior remains
 * deterministic and makes no art-direction provider call until a caller
 * explicitly injects one. Tests and local harnesses can inject a provider stub
 * to prove story -> packet wiring without touching image/story/print providers.
 */
export async function buildArtDirectionPacketFromStory(
  input: ArtDirectionPacketBuildInput,
  deps: ArtDirectionPacketBuilderDeps = {},
): Promise<ArtDirectionPacketBuildResult | null> {
  if (!deps.provider) return null;

  const rawPacket = await deps.provider(input);
  if (rawPacket == null) return null;

  const packet = ArtDirectionPacketSchema.parse(rawPacket);
  const validation = validateStoryboardCompleteness(packet);

  return {
    packet,
    validation,
    generatedAt: (deps.now ?? (() => new Date()))().toISOString(),
    humanReviewStatus: 'needs_review',
    humanReviewNotes: 'Generated by local/provider-injected art-direction builder; pending human review.',
  };
}
